// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyfcgdRwRiuvJAo9JABKUIddxH3RPZ4Y',
    appId: '1:417326694072:web:cd6d83c98124b1c7e13e4d',
    messagingSenderId: '417326694072',
    projectId: 'cleaningscheduledemo',
    authDomain: 'cleaningscheduledemo.firebaseapp.com',
    storageBucket: 'cleaningscheduledemo.firebasestorage.app',
    measurementId: 'G-11HF77TB7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrBxoJN7CA3lnToKCoLWyA-bWqa_epF8',
    appId: '1:417326694072:android:a542c272ad8a6515e13e4d',
    messagingSenderId: '417326694072',
    projectId: 'cleaningscheduledemo',
    storageBucket: 'cleaningscheduledemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCLXPPMtqzPFPyNXx-icDR7HKxdcOX_0',
    appId: '1:417326694072:ios:53ad9fdcfd97faede13e4d',
    messagingSenderId: '417326694072',
    projectId: 'cleaningscheduledemo',
    storageBucket: 'cleaningscheduledemo.firebasestorage.app',
    iosBundleId: 'com.example.cleaningSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCLXPPMtqzPFPyNXx-icDR7HKxdcOX_0',
    appId: '1:417326694072:ios:53ad9fdcfd97faede13e4d',
    messagingSenderId: '417326694072',
    projectId: 'cleaningscheduledemo',
    storageBucket: 'cleaningscheduledemo.firebasestorage.app',
    iosBundleId: 'com.example.cleaningSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfyfcgdRwRiuvJAo9JABKUIddxH3RPZ4Y',
    appId: '1:417326694072:web:65024f2d271df7bfe13e4d',
    messagingSenderId: '417326694072',
    projectId: 'cleaningscheduledemo',
    authDomain: 'cleaningscheduledemo.firebaseapp.com',
    storageBucket: 'cleaningscheduledemo.firebasestorage.app',
    measurementId: 'G-0RXRT2JE6W',
  );
}
