// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcbi91ZpCsonCocvwrf2Y0wyyZ2Qi2vM',
    appId: '1:756959569323:ios:fc140caacc92f985ae9eee',
    messagingSenderId: '756959569323',
    projectId: 'cleaning-schedule-14317',
    storageBucket: 'cleaning-schedule-14317.firebasestorage.app',
    iosBundleId: 'com.web82ORTA.cleaningSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcbi91ZpCsonCocvwrf2Y0wyyZ2Qi2vM',
    appId: '1:756959569323:ios:fc140caacc92f985ae9eee',
    messagingSenderId: '756959569323',
    projectId: 'cleaning-schedule-14317',
    storageBucket: 'cleaning-schedule-14317.firebasestorage.app',
    iosBundleId: 'com.web82ORTA.cleaningSchedule',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRNV7-3WVUYD51arnjYniwslTXf-AknQ',
    appId: '1:756959569323:web:0d5c6c057d87e427ae9eee',
    messagingSenderId: '756959569323',
    projectId: 'cleaning-schedule-14317',
    authDomain: 'cleaning-schedule-14317.firebaseapp.com',
    storageBucket: 'cleaning-schedule-14317.firebasestorage.app',
    measurementId: 'G-LNNVN98BCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUehIlCS2XFMC1EHnU2mUQwKz40PH_81A',
    appId: '1:756959569323:android:32e6f411df380364ae9eee',
    messagingSenderId: '756959569323',
    projectId: 'cleaning-schedule-14317',
    storageBucket: 'cleaning-schedule-14317.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRNV7-3WVUYD51arnjYniwslTXf-AknQ',
    appId: '1:756959569323:web:893c3ea07a0e9d15ae9eee',
    messagingSenderId: '756959569323',
    projectId: 'cleaning-schedule-14317',
    authDomain: 'cleaning-schedule-14317.firebaseapp.com',
    storageBucket: 'cleaning-schedule-14317.firebasestorage.app',
    measurementId: 'G-CMQEQEMN76',
  );

}